CREATE DATABASE `elections`
CREATE TABLE `elections`.`voters` ( `id` INT NOT NULL AUTO_INCREMENT , `pass` VARCHAR(200) NOT NULL , `bhavan` VARCHAR(200) NOT NULL , `president` VARCHAR(200) NOT NULL , `gensec` VARCHAR(200) NOT NULL , `cultsec` VARCHAR(200) NOT NULL , `sportssec` VARCHAR(200) NOT NULL , `smc` VARCHAR(200) NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
